# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x2AuH7l5UG_r0hW8Eyx0NhkffAYHm9BH
"""

import matplotlib.pyplot as plt

import numpy as np

def QTWM(t,a,b,c):
  return (a*t**2+b*(t+c))
hc_a=1.0
hc_b=-2.5
hc_c=3.5
g_values=np.linspace(0,1,100)
hc_temp=QTWM(g_values,hc_a,hc_b,hc_c)
plt.plot(g_values,hc_temp,label="Hardcoded:a={hc_a},b={hc_b},c={hc_c}")
sets=int(input("Enter number of sets:"))
coefficients=[]
for i in range(sets):
  a=float(input("Enter coefficient a:"))
  b=float(input("Enter coefficient b:"))
  c=float(input("Enter coefficient c:"))
  coefficients.append([a,b,c])
for i,(a,b,c) in enumerate(coefficients):
  Temperature=QTWM(g_values,a,b,c)
  plt.plot(g_values,Temperature,label=f"Set {i+1}:a={a},b={b},c={c}")
plt.xlabel("Time")
plt.ylabel("Temperature")
plt.legend()
plt.show()

import numpy as np

import matplotlib.pyplot as plt

def quadratic_models(time,a,b,c):
    temp = a* (time ** 2) + b * time + c
    return temp

def main() :

    time_values = np.linspace(0,10,50)

    with open('/content/se.txt', 'r') as file:
            lines = file.readlines()

    if lines[0].strip().startswith('VALUES'):
        lines = lines[1:]
    for i, line in enumerate(lines):
            a, b, c = map(float, line.split())
            temperature_file_multiple = quadratic_models(time_values, a, b, c)
            plt.plot(time_values, temperature_file_multiple, label=f'File Input Set {i+1} Coefficients')
    plt.xlabel('Time')
    plt.ylabel('Temperature')
    plt.legend()
    plt.title('Multi Set from File')
    plt.show()

main()